### ISSUE TITLE
Broken in nodebb 1.0.0

### ISSUE THREAD

**Issue by tomamoto** [bdharrington7/nodebb-plugin-imgbed#12]
Fatal error prevents nodebb from loading properly.  Here's the stack trace I got.  Disabling node-bb-plugin-imgbed was the only way to get nodebb to load.
_
1/3 17:08 [19349] - error: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-imgbed'
1/3 17:08 [19349] - error:  TypeError: object is not a function
    at Object.Imgbed.init (/opt/nodebb/node_modules/nodebb-plugin-imgbed/library.js:86:13)
    at Object.Imgbed.onLoad [as method] (/opt/nodebb/node_modules/nodebb-plugin-imgbed/library.js:134:12)
    at /opt/nodebb/src/plugins/hooks.js:147:14
    at /opt/nodebb/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/opt/nodebb/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/opt/nodebb/node_modules/async/lib/async.js:209:22)
    at fireStaticHook (/opt/nodebb/src/plugins/hooks.js:136:9)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins/hooks.js:82:5)
    at Plugins.reloadRoutes (/opt/nodebb/src/plugins.js:143:11)
    at /opt/nodebb/node_modules/async/lib/async.js:760:23_

**Comment by bdharrington7** [comment]
@tomamoto  Did you update? What version of the plugin are you running?

**Comment by tomamoto** [comment]
@bdharrington7 Sorry for the lack of clarification.  I started with nodebb-plugin-imgbed v 1.0.1 on NodeBB 0.9.4.  Under these conditions, the plugin was working beautifully.  I then updated around 90 minutes ago to NodeBB 1.0.0, following the recommended procedures and when I attempted to restart nodeBB, my logs showed the error I posted above, causing the startup scripts to retry and eventually fail.  I then had to manually disable nodebb-plugin-imgbed using nodebb reset and was thereby able to start nodebb as expected.

**Comment by tomamoto** [comment]
@bdharrington7 Oh, and this is the part where the actual shutdown is forced:

1/3 18:56 [19742] - error: TypeError: Cannot call method 'get' of undefined
    at Object.Imgbed.parseRaw (/opt/nodebb/node_modules/nodebb-plugin-imgbed/library.js:97:36)
    at Object.Imgbed.parse [as method] (/opt/nodebb/node_modules/nodebb-plugin-imgbed/library.js:115:12)
    at /opt/nodebb/src/plugins/hooks.js:103:12
    at /opt/nodebb/node_modules/async/lib/async.js:375:13
    at Object.iterate [as _onImmediate] (/opt/nodebb/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
TypeError: Cannot call method 'get' of undefined
    at Object.Imgbed.parseRaw (/opt/nodebb/node_modules/nodebb-plugin-imgbed/library.js:97:36)
    at Object.Imgbed.parse [as method] (/opt/nodebb/node_modules/nodebb-plugin-imgbed/library.js:115:12)
    at /opt/nodebb/src/plugins/hooks.js:103:12
    at /opt/nodebb/node_modules/async/lib/async.js:375:13
    at Object.iterate [as _onImmediate] (/opt/nodebb/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
1/3 18:56 [19742] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
1/3 18:56 [19742] - info: [app] Database connection closed.
1/3 18:56 [19742] - info: [app] Web server closed to connections.
1/3 18:56 [19742] - info: [app] Shutdown complete.
[cluster] Child Process (19742) has exited (code: 1, signal: null)
[cluster] Spinning up another process...

**Comment by bdharrington7** [comment]
I just love it when this happens:

```
npm WARN unmet dependency /Users/brian/github/NodeBB/node_modules/nodebb-plugin-imgbed requires xregexp@'3.0.x' but will load
npm WARN unmet dependency /Users/brian/github/NodeBB/node_modules/xregexp,
npm WARN unmet dependency which is version 3.1.0
```

Thaaaaanks npm. 

Thanks for reporting @tomamoto

**Comment by tomamoto** [comment]
@bdharrington7 I've certainly run into similar problems with npm.  Thanks so much for taking the time and effort and fixing this so quickly.
